---
driver:
  name: vagrant
  customize:
    memory: 512
  network:
    - ["private_network", {ip: "10.10.13.21"}]
  ssh:
    insert_key: false


provisioner:
  name: chef_zero
  
driver_config:
  require_chef_omnibus: true

platforms:
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[mywordpress]
    
