driver_plugin: vagrant

provisioner:
  name: chef_zero
  
driver_config:
  require_chef_omnibus: true

platforms:
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[wordpress]
    
