name              'mywordpress'
maintainer        'reancloud'
maintainer_email  'nagaraj.as@reancloud.com'
license           'xxxxx'
description       'install wordpress'
version           '1.0.0'
source_url        'https://github.com/nagarajabalur/mywordpress.git'
issues_url         'https://github.com/nagarajabalur/mywordpress.git'
depends 'database', '>= 1.6.0'
depends 'mysql', '>= 6.0'
depends 'mysql2_chef_gem', '~> 1.0.1'
